### PR TITLE
Stamina damage

### PR DESCRIPTION
**Pull request by kyronkiranov**
Fix for Stamina not resetting to 98 as soon as it goes over 100.

Punches deal 1Brute and 5 Stamina Damage.

Swinging punches costs 2 points of Stamina. Swinging weapons costs 2*weight for said weapon.
This means that the fire axe, one of the heaviest weapons around at "w_class 4" can be swung about 12 times (realistically 15) before you're too tired.
The damage you deal with melee weapons is adjusted by your Stamina like punches, penalties only starting once you reach 50 StamDam.

If you sustain more than 50 Stamina Damage, the StamDam you deal and your chance to hit begins to reduce down to 0 at 100 Stamina Damage.
If your oponent has more than 50 Stamina Damage, you have a chance to knock him down depending on the difference between your Stamina.

### CODE REVIEW

**Comment by kyronkiranov** [comment]
All fully tested by me, it's working as intended without a problem.
This should help make punchs and brawls into a less serious offense. It should no longer be on the same level as attempted murder.
It also fixes Disablers, as they currently only down someone for 1-2 ticks

Merge it, inform the players it's on (so they can get physical with it) and let's see how it goes.
If it's no good you can just revert the merge and if its a matter of tweaking values, that can be done easily.

**Comment by DoctoreMad** [comment]
>Punches deal 1Brute and 5 Stamina Damage.

Can you just change that to at least 2-3 brute or something
100 punches to kill someone sounds retarded
Also does melee protection decrease punch stamina damage and the like?

**Comment by kyronkiranov** [comment]
The idea is that you don't use punches to kill someone. You grab a weapon and bash him, or you strangle him once he goes down.

If you intend to kill someone with your bare hands, 15 punches and he goes out. Grab, strangle and done.

Also yes, armor still applies to damage, at least the brute part.

**Comment by DoctoreMad** [comment]
I mean if a armor softens the blow do you still take stamina damage?

​>Punch a guy in riot armor
​>He starts getting tired

**Comment by kyronkiranov** [comment]
This isn't really part of this code, but that's actually a thing. Armor isn't all the same and some actually allows force to pass through.

Full plate armor for instance, when suffering a hit from blunt weapons will not only cave in but also ring and absorb very little force from the strike, so the user takes the blunt of it, if a bit spread out due to larger contact area.
This is one of the reasons even full plate or chain mail armor saw use of some internal padding of leather or similar flexible materials that could actually soften the concussion part of a blow.

If realism is what bothers you, than that's your answer. The concussion part of a punch, what actually causes stamina damage, is fully capable of bypassing most solid armor anyway.

But honestly, I don't think we need to reach that level of autism right now.

**Comment by Towershield** [comment]
As someone who has worn actual combat armor in an actual combat environment and actually had it help save his life, I'm gonna call your bit on how armor may or may not absorb concussive force a complete and total crap justification for a badly thought out combat system addition.
A kevlar vest with a ballistic plate insert was enough to nullify the concussive force of a vehicle-born IED being detonated less than 20 feet away and kept that force from turning everything behind my ribs into mush.  Furthermore, actual CQC training in the vests before deployment is proof enough, to me at least, that physical strikes to the armored area by human-level force will not tire out the wearer, but the person striking it.
Please, don't use "realism" to justify something that clearly isn't operating on realism in the first place.

**Comment by kyronkiranov** [comment]
Dont know why you're going full navy seal copypasta there, the idea here isnt striving for realism. We can mitigate stam damage with armor or even deal some to the attacker based on how much armor the defender has if you prefered.

Although to be honest, there are already complaints that this is too complicated even without accounting for that detail and tipping the scales even `more` towards armor might not be a good idea.

**Comment by Towershield** [comment]
It's not full navy seal copypasta, it's actual firsthand experience with modern armor that happens to completely contradict how you "think" armor is supposed to work.  
Armor already plays the part it's supposed to play in combat, by softening most blows outright.  Tiring out the wearer with repeated punches to the armored area and rendering the wearer helpless as the attacker then goes for the strangle/kill, while offering zero downsides to the combatant that isn't wearing armor is very lopsided.  

"We can mitigate stam damage with armor or even deal some to the attacker based on how much armor the defender has if you prefered."  The preference is to not have a system that WILL bog down combat.  It was brought up elsewhere that slowing combat down like this will play into your idea of making combat turn-based.   Personally, I can see no other reason to want the speed of combat brought down other than to facilitate other ideas that will make use of the reduced speed.  No thanks.

**Comment by DoctoreMad** [comment]
>and tipping the scales even more towards armor might not be a good idea.

But it barely tips toward armor right now since stuns are still lord, and your PR doesn't change that very much right now. What are you onto?

**Comment by kyronkiranov** [comment]
>  your idea of making combat turn-based
That is not my idea and it's not what this is all about. It merely makes punches non-lethal and balances heavier hard hitting weapons vs smaller light weight but less damaging ones.

>stuns are still lord
Not according to the current codebase where they seem to be nerfed

> your PR doesn't change that very much right now
That's because this PR isn't about Stuns at all to begin with, why did you even brought that up?

**Comment by DoctoreMad** [comment]
​>there are already complaints that this is too complicated even without accounting for that detail and tipping the scales even more towards armor might not be a good idea.
​>But stuns are lord, not armor
​>Why are you mentioning stuns?
Not a mystery.

Its controversial because you can stun people in riot suits by punching them with your bare fists.

**Comment by kyronkiranov** [comment]
You are not making much sense, you were the first person to mention "stuns being lord", despite the fact that this is not true for our current codebase and because this does not touch the stuns at all.
Weaken != Stun in terms of code and nothing in stamina actually uses stuns.

>Its controversial because you can stun people in riot suits by punching them with your bare fists.
And how many punches do you think you'll need for that? Or how many are you gonna take back from the other guy while you have no protection at all?

Is that all? Is that the only problem you have with this? Because sure, it's a simple thing to mitigate or outright cause no stamina damage to targets with armor, if that's what you want.
However Sec Officers (and the Bartender, HoP and Captain) are never gonna take any stamina damage at all with this, meaning punching them is pretty much pointless while they can do normal stam damage to you.

Is that what you want? Have part of the crew immune to this and force the rest towards murder to defend themselves from non-lethal attacks? Cause that can be arranged but I'll be sure to credit the idea.

Or maybe we can stop with this armor autism and just accept that it will mitigate the Brute part of fists, the part that causes permanent damage anyway, and that anyone intent on murder isn't gonna bother with fists anyway.

**Comment by Towershield** [comment]
>Or maybe we can stop with this armor autism and just accept that it will mitigate the Brute part of fists, the part that causes permanent damage anyway

 Except Brute damage isn't permanent, healing _is_ a thing and Medbay and first aid kits exist for that very reason.  The players know this and adjust themselves accordingly if they're not out to put someone in crit during a bar brawl or "duel".   I've borne witness to D&D sessions on the station where fist fights were used to resolve conflicts and any damage that was sustained was patched up.  Nobody held any grudges over losing health from getting slugged because the damage was ultimately temporary.

> Is that what you want? Have part of the crew immune to this and force the rest towards murder to defend themselves from non-lethal attacks? Cause that can be arranged but I'll be sure to credit the idea.
Stuff like this and your "armor autism" quip are entirely unnecessary.  If you can't handle your code being rightly scrutinized and criticized then perhaps you should cease with the absurd justifications that prompt "armor autism" in the first place.

**Comment by kyronkiranov** [comment]
You are being obtuse on purpose now. Brute is permanent in the sense that it doesn't go away on it's own, unlike Stamina Damage. And I'm not gonna bother to reply to annedotal evidence since that's not what we are talking about anyway.

>If you can't handle your code being rightly scrutinized
This is as far from "rightly scrutinized" as possible. It's all a bunch of dumb conjectures about what it actually does, about how it is going to work and about what my real idea behind this is. None of it is true but since it happens inside your head, that's all it matters.

You can fork over my code and try it locally to actually test how it affects combat, so I won't entertain this discussion anymore, especially since both of you are the ones that started with the "it's not realistic because armor!!1!" when all this change was meant to be was for non-lethal combat to be an option open to anyone at any time.

If you want to over meta analyze this instead, actually believing for a second that punches will ever beat someone with literally any weapon at all as if that was the point, feel free to do so. It's not, it never was, and your bad attempt at misrepresenting this idea tells more about you than about the code.

BTW, good going there with the "you just want a turn based combat". You just confirmed yourself to be the autist that rants in every thread about anything I suggest regardless of what it is. In other words, your criticism is worthless since you're never really critiquing my idea.

**Comment by Towershield** [comment]
>You just confirmed yourself to be the autist that rants in every thread about anything I suggest regardless of what it is. In other words, your criticism is worthless since you're never really critiquing my idea.

Yeah nah.  The only posts I've made in any SS13 threads since Sierra's station went offline involved the small map fixes I've made. That's it.  Not everyone that disagrees with you is an autist that rants about you elsewhere on the internet.

**Comment by kyronkiranov** [comment]
Which is why you repeated verbatin the "argument" you used last thread right? Get fucked, not everyone is as dumb and naive as you are.

I bet that if I suggested the Oreos idea, you'd be here complaining how it's "giving gunpowder to shiters" and a dumb idea as well. Whatever problem you have with me (or more likely with Koriath) it's got nothing to do with the code I write and if you're gonna critize me instead of my work, then I might as well regard everything you write as shitposting and personal (shitty) opinions.

**Comment by DoctoreMad** [comment]
>If realism is what bothers you, than that's your answer. The concussion part of a punch, what actually causes stamina damage, is fully capable of bypassing most solid armor anyway.

I'm pretty sure you started the realism argument here!

**Comment by Towershield** [comment]
>Whatever problem you have with me (or more likely with Koriath) it's got nothing to do with the code I write and if you're gonna critize me instead of my work, then I might as well regard everything you write as shitposting and personal (shitty) opinions.

You're the one taking it personally, not me.  Frankly, I couldn't care any less about you or your brother on a personal level.  All I've said here has been entirely about the stamina system you're proposing and why I think it's a bad idea and shouldn't be added to the game as-is.  I've backed up my position with real experience and used it to try to point out that your realism approach, which DoctoreMad has highlighted above, is not actually how it works.

I also stand by what I said about your intent to slow down combat to turn-based speed and not merely because I agree with whoever said it in the thread.  You said yourself earlier, "The idea is that you don't use punches to kill someone. You grab a weapon and bash him, or you strangle him once he goes down.".  Under your system someone would have to punch an armored target enough to weaken them to the point they collapse which will take forever compared to the current speed of combat.  You may as well just turn combat into old school turn-based Final Fantasy at that point since it'll take forever to resolve combat like that.

**Comment by RoleplayRascal** [comment]
Buddies, please, this isn't the thread, Don't shitpost eachother too hard here!
I should also stress my original opinion still remains on this change, as the constant arguing between you lot only proves that you can dig harder when you're already rock bottom.
I do not like this change for many reasons. I think changing combat as a whole in regards to stamina is a terrible mechanic, which others have said, will only slow down combat and make it less exciting and fun to actually play. The change prioritizes RNG, and as you should know, RNG does not and should not belong in a combat system as it negates any form of skill and bases it on luck.
In our current combat system, if you are low on stamina or naturally slow due to not eating, you still have a slight chance of winning a fight. With this system, if you get below 50 stamina, which, if we haven't forgotten the toy items which have been made to purposefully kill your stamina, You're at the disadvantage, even if you're slow or not. The higher chance to knock someone over won't even matter because you'll be wasting time attempting to land hits against a stable opponent.
This stamina change doesn't do anything towards players who use ranged weapons, making e-guns and other ranged weapons more of a viable option in regards of not getting fucked. Which eventually makes rushing the armory or getting a way to stun or disable much more valuable then using melee weapons.
Outside of the forced RNG, It feels like this update is intending on buffing ranged by gimping melee into a mess of who has the better stamina going into the fight.
I'm sorry if this didn't make sense, I haven't slept in a day.
Please forgive me for any mistakes I've made. Thanks.

**Comment by kyronkiranov** [comment]
RoleplayRascal
This does not slow down combat and does not prioritize RNG at all.
Why are so many assumptions there when there's a clear and simple explanation on the very first post and the list of changes is freely available? Why are you basing your opinion on hearsay instead of actually looking at things on your own?

The only random part of this is the chance of knockdown when you're tired and someone socks you. Everything else is 100% deterministic in it's costs and how it affects the player.

And please, said knockdown chance only happens if your oponent uses his punches, it does not affect any other form or melee combat.

Stamina isn't supposed to do anything regarding ranged weapons because not only that makes little sense, it's an extra burden on top of needing ammo\energy.
That's the disadvantage of ranged weapons, that they need ammo which (for the most part) does not regenerate unlike stamina.

Any advantage you will have with ranged weapons you already have them as things are currently, this does not change that balance at all. Punches are not and never were viable to the point that throwing tiles is a far more robust solution. Everyone always defaults to a crowbar or toolbox to cause double the damage with every strike because relying on punchs for random Weakens is relying on RNG.

By the way, that's a thing you don't seem to acknowledge or possibly know, there's already RNG out the ass regarding punches, namely 10% chance of missing and 10% of "critical hit". Why is it a problem to remove this RNG and replace it with something that only happens once you are tired?

Stuns are not that valuable considering how short they stun people, has no one seriously looked at that part of the code yet?

The "forced RNG" happens stricly if one condition is verified first, unlike the current system where you ALWAYS have RNG associated with punches and where punchs are pretty much a crowbar that deals less damage. There's also no RNG associated with using any weapon that's not your punchs and it's not like melee combat against ranged wasn't all about Disarm spam anyway.


For fuck sake, this was a change to give everyone a chance for non-lethal combat, to make punches something less serious on most ocasions and to make them different from other weapons by dealing a different sort of damage while giving use to Stamina when almost nothing else does besides Disablers and Hallucinations.
This is not supposed to give you a means to fight against armored oponents, this is not supposed to be a new 1337 tactic to take down traitors, this is not supposed to be "an attempt at slowing down combat".

And despite the fact that this is all pretty well explained and every file and change is up for you guys to see, you'll still default to believe the shitpost like it's a valid TL;DR of what this does!
THERE'S NO RNG IF YOU GRAB A CROWBAR AND START SWINGING!
WHY ARE YOU PLAYING DUMB!?

**Comment by kyronkiranov** [comment]
Enough is enough. This merge request has been up for 3 days without anything said by the maintainer, it's pretty clear it's never gonna be merged and I won't entertain this charade any more.

It was a simple change that does not change the "serious" combat with weapons as much as you'd expect (you could swing an axe about 15 times before anything serious started happening to you and 4 swings kill a spessmen)

And yet everything about this is being misconstrued, from what it actually does to the purpose behind it.
Some of you I'll attribute it to stupidity. You'd rather believe what is told to you than check things on your own.
Other's I'll fully atribute to malice as you have nothing logically relevant to say about the idea, only complaints about the author.

If this is how things are going to do and merges are accepted\ignored based on how popular the author behind them is, then I don't expect a great future for a server made for an anonymous culture, and I expected Chaos at least to understand this better than anyone else.
Can't wait to see who's gonna be the new boogeyman since I'm out.

**Comment by chaosyourgod** [comment]
nigger I said I'd wait on it till the weekend so that I can get a a in server pol at prime time with our most on, I had a decent idea of what we could do with it but I do not want to force shit on people till we've got a greater understanding of what people actually want. my stance still stands I want your coding, we want your coding. not your ideafagging. stop being an over emotional girl and LISTEN to what people are saying for fucking once please

**Comment by kyronkiranov** [comment]
Shut it you cunt, you could test it on lowpop where it affects the least amount of people. You could test it on your own as well and report back. You could have at least said something here.
You have no fucking excuse.

This is an actual merge request, not ideafagging, you buzzword spouting faggot. The idea is complete, it's coded and it's ready to be tested. I don't ideafag, I actually do whatever I want to see done instead of asking others to do it for me.

Now YOU stop being an emotional sissy girl, afraid that everyone will run away from the server just because you test something that might not be popular and revert it afterwards (not that that's gonna happen, I fully trust my idea).

Now this comment section is full of faggots blatantly lying about what this is with no comment from anyone but me saying the contrary. I've already heard from Flammenwerfer that 8chanserverhost has the condition that "no Koriath code is to be implemented" and that will mean me as well because you faggots actually fell for the shitposters because why the fuck not? Best to believe a simple lie than discerning the truth on your own.

Get fucked, code your own shit.

**Comment by RoleplayRascal** [comment]
Stop overreacting. I do not tolerate disrespect towards people who do not deserve it, If you want to be angry at someone, be angry at me. This is petty drama, and this looks extremely childish to people from the outside who are looking in.
I stated with full transparency that I do not wish to add in your code because I simply dislike the idea. I believe that you and your lovely brother are great coders, but the ideas that come forth are not as decent, in my opinion, as I hoped. I do not understand how you are not getting this. We're not pushing you back, we're not fucking telling you to fuck off, we're telling you that we do not need changes to certain things, we need things that are fixed, we need things to be fucking fun. How is this so fucking hard to understand. I do not wish to push you away, Kyron. I don't. I just want to change the direction of what you code. Thats all. If you don't like the idea of that, then don't make a fuss and just leave, because this is so fucking stupid, how I have to say this shit again and again just to get it into your head.
By the way, Derflammenwerfer was denied as an admin because he attempted to start arguments against the admins. When he was told he was denied, he promptly fucked off. I would not be shocked if he had a negative opinion towards both the server and the administrators.
Thank you for reading.

**Comment by kyronkiranov** [comment]
And I do not tolerate disrespect towards me or dumb representations of my work, thank you very much.

You stated that one of the reasons why you though this was a bad idea is because of the RNG.
Despite the fact you already have a much worse RNG currently.
Despite the fact I actually removed most of the RNG and merely adapted something that's already present in the Boxing Martial Art but even toned it down. Severely.
Did you even checked the file to see what the odds of someone being knocked out by RNG actually are?

You can try to tell people what they should be doing all you want. You'll be getting nothing but a big fat middle finger to stick it up your ass because people code what they like and what they want and you choose to implement it or not.

You want someone to code your ideas (which makes you an ideafag by the way), you better pay them because no one is gonna do what's essentially a passion job for something they have no passion for.

You can dislike the idea all you want. You can even refuse to merge it.
But misrepresenting it, playing dumb or even trying to assume my motives, that I will never accept nor stand by!

**Comment by kyronkiranov** [comment]
Oh and by the way, for all the "you can knock someone out in full riot gear!", anyone can currently go to the Rec Area, grab the Boxing Gloves and deal 5-8 StamDam to anyone.
That's even more than what's present in my commit.

What's better is that, not only you have RNG on the damage, (5-8), once you hit 50 StamDam on your target, you'll have his StamDam as a chance for knockout, meaning it starts at 50% and there's even -+15% extra chance on top of this for some more RNG!

And I haven't heard any stories about a lone man out-boxing an armed Officer yet, have you?

So get fucked the lot of you, you don't even know the game you're hosting and you can't even be arsed to know it but I'll be dammend if you don't have strong opinions about those that actually know this shit back and forth!

**Comment by RoleplayRascal** [comment]
I'm terribly sorry, but I simply cannot take you seriously anymore. This is too funny to me.
I don't know whether its because you're so ignorant to what I'm saying or because of the line
"You can dislike the idea all you want. You can even refuse to merge it.
But misrepresenting it, playing dumb or even trying to assume my motives, that I will never accept nor stand by!"
I just, I don't know if I can continue living my man, I'll be frank, you know.
Okay so, for starters, The only thing wrong with your ideas is how you attempt to change the fundamentals of certain things without improving to it. Making the stamina bar an "Energy bar" is quite fucking gay.
Secondly, Yes, I am a massive ideafag. I like to make fun ideas that improve on the game instead of changing it.
Thirdly, What stops you from testing out your own code publicly? Why does it have to be chaos and my server? If I actually had the ability to try your code, then maybe I'd might enjoy it and go "yeah this is pretty good, i mean concept wise it sounds like shit but i think the execution was done perfectly". The reason why we're so hesitant on testing code on our server is because it does scare off players. This may be hard to believe, but generally if the public decides that the code is ass, and we put it on our server, then people will refuse to play on our server. We'll become another gitgud.
Lastly, and I do ask, please calm down. I don't like dealing with kids my friend. I believe we should all take a lovely walk outside and enjoy the fresh air.
Thank you.

**Comment by kyronkiranov** [comment]
You can take your condescending tone and shove it up your ass, we're past the point of being polite and fake smiles and pleasantries are far more gay than an "energy bar".

>The only thing wrong with your ideas is how you attempt to change the fundamentals of certain things without improving to it.

I removed the RNG of unarmed combat and replaced it with a deterministic system. That's not improving it?
I made unarmed combat something different, a non-lethal option, so it's not just a worse weapon than literally anything else on the station. I not only gave more options, I made unarmed combat viable in certain situations. That's not improving it?
I made punches a far less serious issue so people can do it for sport or self defense without needing the gloves (a far more gay resctriction than an energy bar). That's not improving it?
I made it so using a knife instead of an axe has a point to it so every weapon is still viable to a degree. That's not improving it?
I made it so running away or staying put matters more, giving people a chance to run away from their attackers. That's not improving it?
I made punches a far superior self-defense weapon than telescopic batons ever were. That's not improving it?

Just what the fuck do you think Stamina is to begin with? It was already a gay system, coded exclusively so Hallucinations could damage you without actually killing you. That's all it was made to do, Disablers came next because "hey what if we try to create an alternative to tasers, but let's not put much effort into it?" which is why Disablers are still shit because you faggots still haven't fixed Stamina > 100.
Stamina doesn't become fucking gay by turning it into an energy bar, it was always gay to begin with, know your fucking history, man.

I already tested my code. It works, it mitigates damage, deals damage and everything works fine. No bug here. What I need now is player input. I need 10 or more people running around in an every day situation aboard SS13 punching the shit out of each other to see how it goes. I can't test this alone and I don't have neither a server or about 10 guys to join up and do me the favour.
And it would be pointless to begin with since all I'd learned would be their opinion which matters none for another server. Vorecode is tested quite well in Citadel, should we implement it on this server?

The public can't decide what the code is until it's implemented and tested. Until that happens the only thing the public can decide is what the speculation regarding what it can be is.
And you can choose to work that way if you want, avoiding becoming another Gitgud and instead becoming another TG where nothing new or fun is ever implemented because it's new and scary.

>I don't like dealing with kids my friend.
And I don't like dealing with people that behave like kids despite being grown men. The age argument on the internet is pretty fucking retarded and you should know it unless you're underage yourself.

**Comment by RoleplayRascal** [comment]
Okay, I've had enough. Just set up your own fucking server and test the code on there publicly, or better yet, fork the fucking codebase and put your fucking code on there and i'll do it myself.

**Comment by Towershield** [comment]
>I can't test this alone and I don't have neither a server or about 10 guys to join up and do me the favour.

Perhaps you should have thought about that before acting like a complete asshole to the server host.

**Comment by kyronkiranov** [comment]
It was already forked you cock mongler! You could have clicked on my profile and downloaded my code to test it yourself, for fuck's sake!

You want it now, you're gonna have to accept the merge and test it locally instead of uploading it to the server. Revert it afterwards if you still don't like it.

I already deleted my fork and I ain't gonna bother writing code for this server again until I get an apology.
You completely misrepresented my idea for no reason at all, you've ignored that Punching Gloves are fucking worse than what I wrote and they are still a part of the game, you've had multiple oportunities to test this on your own.
And what's worse, that other retarded idea about giving the crew free gunpowder with just hacking or a coin was already merged with no poll and no discussion in the community.

So shove it, I don't believe this is about the idea when something that retarded passes right by with no questions asked and yet this is so ignored you don't even know what it actually does.

@Towershield 
Perhaps you should shut the fuck up and go back to shitpost somewhere else about your extensive experience with ceramic armor and your 300 confirmed absorbed blasts.

**Comment by RoleplayRascal** [comment]
Okay, nevermind. Forget everything I've said. Do me a favour and please leave. I'm no longer going to deal with you anymore.

**Pull request closed without merging**
