### PR TITLE
Spirit Board and Endround CKey's

### PR DESCRIPTION
**Pull request by kyronkiranov**
Spirit Board is now renamed Ouija Board.
It still requires at least 2 people, but ghosts can talk a bit faster and the more people around, the faster they can talk (less 5 ticks per person).
It also works at 50% light instead of only 20%.

Endround reports now see the anonymous_key instead of CKeys.

### CODE REVIEW

**Comment by chaosyourgod** [comment]
you realize our station doesn't have a spirit board so one would have to be put in

**Comment by kyronkiranov** [comment]
Oh for fuck's sake...
I can map one in the chapel or the library, I suppose but that would require using the map merge tool to avoid conflicts. Can't someone with access to this hub add it instead and avoid this problem?

**Comment by chaosyourgod** [comment]
no one really wants the oujia board but the ckey fixes are alright, make a new PR with just that please

**Comment by kyronkiranov** [comment]
It was a change requested in a previous thread and you know very well it's "not wanted" because it was coded by me, but whatever. You pander to the players you want.

**Comment by chaosyourgod** [comment]
don't be like that babe, people liked the anonymous code you did and that was written by you

**Comment by kyronkiranov** [comment]
Mate, not one reason has been given against the spirit board. Refusing this commit because "it's not popular" doesn't make any sense, especially since it was indeed requested in the previous thread, which is why I even went to check the code on this. At worst it literally does nothing since there isn't even a board on the station.

If you're gonna refuse merge requests because they aren't popular then I can't code anything as nothing I'll ever code will be popular in the threads for obvious reasons.

Fun exercize, ask one of the other guys to write line-by-line the commit for the spirit board.
See if their idea is just as unpopular because of the content or if suddendly nobody minds because it's someone else doing it.

**Comment by DoctoreMad** [comment]
Wait I don't get it, why wasn't this merged

**Comment by chaosyourgod** [comment]
>since it was indeed requested in the previous thread
the guy who suggested it replied back to me saying he doesn't care since it was for people whining about the chap 

>If you're gonna refuse merge requests because they aren't popular
I refused it simply because I didn't want to add some bit of code which changes something which isn't in our code base yet 

>See if their idea is just as unpopular
I went through this kinda thing on sierras server, my reasoning isn't because you're unpopular and I am not throwing you under a bus. everyone on board is fine having you code so long as you're not treating the server as your personal testing box.

**Comment by DoctoreMad** [comment]
I was hoping it wasn't that.
My advice would be to _just merge it_, I mean that's just dumb. Ouija Board changes are a improvement overall so why cut off and only do the "Endround ckeys are hidden" thing?

**Comment by chaosyourgod** [comment]
it's not really an improvement if there's nothing to improve upon in the first place and if it was put in after the changes then it would just overwrite would it not? also I'm against taking nu/tg/ shit all the time tbh with you

**Pull request closed without merging**
